name: sync-images

env:
  IMAGE_GROUP: ${{ vars.IMAGE_GROUP }}
  IMAGE_REGION: ${{ vars.IMAGE_REGION }}
  ACCESS_KEY: ${{ secrets.ACCESSKEY }}
  SECRET_ACCESS_KEY: ${{ secrets.SECRETACCESSKEY }}
  IMAGES: ${{ github.event.inputs.images }}


on:
  push:
    branches: [ main ]
    paths:
      - 'images.txt'
  workflow_dispatch:
    inputs:
      images:
        description: 'images name'
        required: true
        default: ''

jobs:
  sync-images:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: write images.txt
        run: |
          if [ -n "${{ env.IMAGES }}" ]; then
            echo "images info is not empty"
            echo  ${{ env.IMAGES }} > images.txt
          fi
      - name: Login to Huawei Cloud SWR
        uses: huaweicloud/swr-login@v2.1.0
        with:
          region: ${{ env.IMAGE_REGION }}
          access-key-id: ${{ env.ACCESS_KEY }}
          access-key-secret: ${{ env.SECRET_ACCESS_KEY }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.4.0
      - name: Use Skopeo Tools Sync Image to swr
        run: |
          #!/usr/bin/env bash
          skopeo --version
          while IFS= read -r line || [ -n "$line" ]; do
            # 忽略空行与注释
            if [[ -z "$line" || "$line" =~ ^# ]]; then
              continue
            fi
            # 处理新格式和旧格式
            if [[ "$line" =~ \  ]]; then
              # 新格式: bash:latest bash:5
              origin=$(echo "$line" | awk '{print $1}')
              new_image=$(echo "$line" | awk '{print $2}')
              image_name=$(echo "$new_image" | cut -d':' -f1)
              image_tag=$(echo "$new_image" | cut -d':' -f2)
            else
              # 旧格式: bash:5
              origin=$(echo "$line")
              image_name=$(echo "$origin" | rev | cut -d':' -f2- | rev | awk -F'/' '{print $NF}')
              image_tag=${origin#*:}
            fi
            destination=swr.${{ env.IMAGE_REGION }}.myhuaweicloud.com/${{ env.IMAGE_GROUP }}/$image_name:$image_tag
            echo "origin: $origin ==> destination: $destination"
            skopeo copy --all docker://$origin docker://$destination 
          done < images.txt